// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"clock-in/app/worktime/job/internal/biz"
	"clock-in/app/worktime/job/internal/conf"
	"clock-in/app/worktime/job/internal/data"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(server *conf.Server, confData *conf.Data, logger log.Logger) (*biz.WorktimeUsecase, error) {
	worktimeServiceClient := data.NewWorkTimeClient(confData)
	dataData, err := data.NewData(confData, worktimeServiceClient, logger)
	if err != nil {
		return nil, err
	}
	workTimeRepo := data.NewWorkTimeRepo(dataData, logger)
	worktimeUsecase := biz.NewWorktimeUsecase(workTimeRepo, logger)
	return worktimeUsecase, nil
}
