// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"clock-in/app/clockin/admin/internal/biz"
	"clock-in/app/clockin/admin/internal/conf"
	"clock-in/app/clockin/admin/internal/data"
	"clock-in/app/clockin/admin/internal/server"
	"clock-in/app/clockin/admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	worktimeServiceClient := data.NewWorkTimeClient(confData)
	dataData, err := data.NewData(confData, worktimeServiceClient, logger)
	if err != nil {
		return nil, nil, err
	}
	workTimeRepo := data.NewWorkTimeRepo(dataData, logger)
	clockinUsecase := biz.NewClockinUsecase(workTimeRepo, logger)
	clockinAdminService := service.NewClockinServicee(clockinUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, clockinAdminService, logger)
	httpServer := server.NewHTTPServer(confServer, clockinAdminService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
