// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/worktime/service/v1/worktime.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Day    int64 `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Minute int64 `protobuf:"varint,3,opt,name=minute,proto3" json:"minute,omitempty"`
}

func (x *WorkTime) Reset() {
	*x = WorkTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkTime) ProtoMessage() {}

func (x *WorkTime) ProtoReflect() protoreflect.Message {
	mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkTime.ProtoReflect.Descriptor instead.
func (*WorkTime) Descriptor() ([]byte, []int) {
	return file_api_worktime_service_v1_worktime_proto_rawDescGZIP(), []int{0}
}

func (x *WorkTime) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkTime) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *WorkTime) GetMinute() int64 {
	if x != nil {
		return x.Minute
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day    int64 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	User   int64 `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Moment int64 `protobuf:"varint,3,opt,name=moment,proto3" json:"moment,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_worktime_service_v1_worktime_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Record) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *Record) GetMoment() int64 {
	if x != nil {
		return x.Moment
	}
	return 0
}

type GetUserWorkTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User int64   `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Day  []int64 `protobuf:"varint,2,rep,packed,name=day,proto3" json:"day,omitempty"`
}

func (x *GetUserWorkTimeRequest) Reset() {
	*x = GetUserWorkTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserWorkTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWorkTimeRequest) ProtoMessage() {}

func (x *GetUserWorkTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWorkTimeRequest.ProtoReflect.Descriptor instead.
func (*GetUserWorkTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_worktime_service_v1_worktime_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserWorkTimeRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *GetUserWorkTimeRequest) GetDay() []int64 {
	if x != nil {
		return x.Day
	}
	return nil
}

type GetUserWorkTimeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Worktime []*WorkTime `protobuf:"bytes,1,rep,name=worktime,proto3" json:"worktime,omitempty"`
}

func (x *GetUserWorkTimeReply) Reset() {
	*x = GetUserWorkTimeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserWorkTimeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWorkTimeReply) ProtoMessage() {}

func (x *GetUserWorkTimeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWorkTimeReply.ProtoReflect.Descriptor instead.
func (*GetUserWorkTimeReply) Descriptor() ([]byte, []int) {
	return file_api_worktime_service_v1_worktime_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserWorkTimeReply) GetWorktime() []*WorkTime {
	if x != nil {
		return x.Worktime
	}
	return nil
}

type CreateWorkTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   int64     `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Record []*Record `protobuf:"bytes,2,rep,name=record,proto3" json:"record,omitempty"`
}

func (x *CreateWorkTimeRequest) Reset() {
	*x = CreateWorkTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkTimeRequest) ProtoMessage() {}

func (x *CreateWorkTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkTimeRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_worktime_service_v1_worktime_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkTimeRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CreateWorkTimeRequest) GetRecord() []*Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type CreateWorkTimeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateWorkTimeReply) Reset() {
	*x = CreateWorkTimeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkTimeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkTimeReply) ProtoMessage() {}

func (x *CreateWorkTimeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_worktime_service_v1_worktime_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkTimeReply.ProtoReflect.Descriptor instead.
func (*CreateWorkTimeReply) Descriptor() ([]byte, []int) {
	return file_api_worktime_service_v1_worktime_proto_rawDescGZIP(), []int{5}
}

var File_api_worktime_service_v1_worktime_proto protoreflect.FileDescriptor

var file_api_worktime_service_v1_worktime_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x22, 0x44, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x22, 0x46, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x64, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x3e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22,
	0x55, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3d, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x08, 0x77, 0x6f,
	0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x64, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x15, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x32, 0xf4, 0x01, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x71, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x57, 0x6f, 0x72,
	0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6e, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x40, 0x0a, 0x17, 0x61, 0x70,
	0x69, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x23, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x2d, 0x69,
	0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_worktime_service_v1_worktime_proto_rawDescOnce sync.Once
	file_api_worktime_service_v1_worktime_proto_rawDescData = file_api_worktime_service_v1_worktime_proto_rawDesc
)

func file_api_worktime_service_v1_worktime_proto_rawDescGZIP() []byte {
	file_api_worktime_service_v1_worktime_proto_rawDescOnce.Do(func() {
		file_api_worktime_service_v1_worktime_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_worktime_service_v1_worktime_proto_rawDescData)
	})
	return file_api_worktime_service_v1_worktime_proto_rawDescData
}

var file_api_worktime_service_v1_worktime_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_worktime_service_v1_worktime_proto_goTypes = []interface{}{
	(*WorkTime)(nil),               // 0: api.worktime.service.v1.WorkTime
	(*Record)(nil),                 // 1: api.worktime.service.v1.Record
	(*GetUserWorkTimeRequest)(nil), // 2: api.worktime.service.v1.GetUserWorkTimeRequest
	(*GetUserWorkTimeReply)(nil),   // 3: api.worktime.service.v1.GetUserWorkTimeReply
	(*CreateWorkTimeRequest)(nil),  // 4: api.worktime.service.v1.CreateWorkTimeRequest
	(*CreateWorkTimeReply)(nil),    // 5: api.worktime.service.v1.CreateWorkTimeReply
}
var file_api_worktime_service_v1_worktime_proto_depIdxs = []int32{
	0, // 0: api.worktime.service.v1.GetUserWorkTimeReply.worktime:type_name -> api.worktime.service.v1.WorkTime
	1, // 1: api.worktime.service.v1.CreateWorkTimeRequest.record:type_name -> api.worktime.service.v1.Record
	2, // 2: api.worktime.service.v1.WorktimeService.GetUserWorkTime:input_type -> api.worktime.service.v1.GetUserWorkTimeRequest
	4, // 3: api.worktime.service.v1.WorktimeService.CreateWorkTime:input_type -> api.worktime.service.v1.CreateWorkTimeRequest
	3, // 4: api.worktime.service.v1.WorktimeService.GetUserWorkTime:output_type -> api.worktime.service.v1.GetUserWorkTimeReply
	5, // 5: api.worktime.service.v1.WorktimeService.CreateWorkTime:output_type -> api.worktime.service.v1.CreateWorkTimeReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_worktime_service_v1_worktime_proto_init() }
func file_api_worktime_service_v1_worktime_proto_init() {
	if File_api_worktime_service_v1_worktime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_worktime_service_v1_worktime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_worktime_service_v1_worktime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_worktime_service_v1_worktime_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserWorkTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_worktime_service_v1_worktime_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserWorkTimeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_worktime_service_v1_worktime_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_worktime_service_v1_worktime_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkTimeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_worktime_service_v1_worktime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_worktime_service_v1_worktime_proto_goTypes,
		DependencyIndexes: file_api_worktime_service_v1_worktime_proto_depIdxs,
		MessageInfos:      file_api_worktime_service_v1_worktime_proto_msgTypes,
	}.Build()
	File_api_worktime_service_v1_worktime_proto = out.File
	file_api_worktime_service_v1_worktime_proto_rawDesc = nil
	file_api_worktime_service_v1_worktime_proto_goTypes = nil
	file_api_worktime_service_v1_worktime_proto_depIdxs = nil
}
