// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/clockin/admin/v1/clockin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day    int64 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Minute int64 `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
}

func (x *WorkTime) Reset() {
	*x = WorkTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_clockin_admin_v1_clockin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkTime) ProtoMessage() {}

func (x *WorkTime) ProtoReflect() protoreflect.Message {
	mi := &file_api_clockin_admin_v1_clockin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkTime.ProtoReflect.Descriptor instead.
func (*WorkTime) Descriptor() ([]byte, []int) {
	return file_api_clockin_admin_v1_clockin_proto_rawDescGZIP(), []int{0}
}

func (x *WorkTime) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *WorkTime) GetMinute() int64 {
	if x != nil {
		return x.Minute
	}
	return 0
}

type UserWorkTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     int64       `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Worktime []*WorkTime `protobuf:"bytes,2,rep,name=worktime,proto3" json:"worktime,omitempty"`
}

func (x *UserWorkTime) Reset() {
	*x = UserWorkTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_clockin_admin_v1_clockin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserWorkTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWorkTime) ProtoMessage() {}

func (x *UserWorkTime) ProtoReflect() protoreflect.Message {
	mi := &file_api_clockin_admin_v1_clockin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWorkTime.ProtoReflect.Descriptor instead.
func (*UserWorkTime) Descriptor() ([]byte, []int) {
	return file_api_clockin_admin_v1_clockin_proto_rawDescGZIP(), []int{1}
}

func (x *UserWorkTime) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *UserWorkTime) GetWorktime() []*WorkTime {
	if x != nil {
		return x.Worktime
	}
	return nil
}

type GetWorkTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User []int64 `protobuf:"varint,1,rep,packed,name=user,proto3" json:"user,omitempty"`
	Day  []int64 `protobuf:"varint,2,rep,packed,name=day,proto3" json:"day,omitempty"`
}

func (x *GetWorkTimeRequest) Reset() {
	*x = GetWorkTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_clockin_admin_v1_clockin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkTimeRequest) ProtoMessage() {}

func (x *GetWorkTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clockin_admin_v1_clockin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkTimeRequest.ProtoReflect.Descriptor instead.
func (*GetWorkTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_clockin_admin_v1_clockin_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkTimeRequest) GetUser() []int64 {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetWorkTimeRequest) GetDay() []int64 {
	if x != nil {
		return x.Day
	}
	return nil
}

type GetWorkTimeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*UserWorkTime `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetWorkTimeReply) Reset() {
	*x = GetWorkTimeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_clockin_admin_v1_clockin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkTimeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkTimeReply) ProtoMessage() {}

func (x *GetWorkTimeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_clockin_admin_v1_clockin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkTimeReply.ProtoReflect.Descriptor instead.
func (*GetWorkTimeReply) Descriptor() ([]byte, []int) {
	return file_api_clockin_admin_v1_clockin_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkTimeReply) GetData() []*UserWorkTime {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_clockin_admin_v1_clockin_proto protoreflect.FileDescriptor

var file_api_clockin_admin_v1_clockin_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69,
	0x6e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x22, 0x5e,
	0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x3a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b,
	0x69, 0x6e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x3a,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x4a, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xa5, 0x01, 0x0a, 0x13, 0x43, 0x6c, 0x6f, 0x63, 0x6b,
	0x69, 0x6e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x8d,
	0x01, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x22, 0x21, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x67, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x3a, 0x01, 0x2a, 0x42, 0x3a,
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x20, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x2d,
	0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x2f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_clockin_admin_v1_clockin_proto_rawDescOnce sync.Once
	file_api_clockin_admin_v1_clockin_proto_rawDescData = file_api_clockin_admin_v1_clockin_proto_rawDesc
)

func file_api_clockin_admin_v1_clockin_proto_rawDescGZIP() []byte {
	file_api_clockin_admin_v1_clockin_proto_rawDescOnce.Do(func() {
		file_api_clockin_admin_v1_clockin_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_clockin_admin_v1_clockin_proto_rawDescData)
	})
	return file_api_clockin_admin_v1_clockin_proto_rawDescData
}

var file_api_clockin_admin_v1_clockin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_clockin_admin_v1_clockin_proto_goTypes = []interface{}{
	(*WorkTime)(nil),           // 0: api.clockin.admin.v1.WorkTime
	(*UserWorkTime)(nil),       // 1: api.clockin.admin.v1.UserWorkTime
	(*GetWorkTimeRequest)(nil), // 2: api.clockin.admin.v1.GetWorkTimeRequest
	(*GetWorkTimeReply)(nil),   // 3: api.clockin.admin.v1.GetWorkTimeReply
}
var file_api_clockin_admin_v1_clockin_proto_depIdxs = []int32{
	0, // 0: api.clockin.admin.v1.UserWorkTime.worktime:type_name -> api.clockin.admin.v1.WorkTime
	1, // 1: api.clockin.admin.v1.GetWorkTimeReply.data:type_name -> api.clockin.admin.v1.UserWorkTime
	2, // 2: api.clockin.admin.v1.ClockinAdminService.GetWorkTime:input_type -> api.clockin.admin.v1.GetWorkTimeRequest
	3, // 3: api.clockin.admin.v1.ClockinAdminService.GetWorkTime:output_type -> api.clockin.admin.v1.GetWorkTimeReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_clockin_admin_v1_clockin_proto_init() }
func file_api_clockin_admin_v1_clockin_proto_init() {
	if File_api_clockin_admin_v1_clockin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_clockin_admin_v1_clockin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_clockin_admin_v1_clockin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserWorkTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_clockin_admin_v1_clockin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_clockin_admin_v1_clockin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkTimeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_clockin_admin_v1_clockin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_clockin_admin_v1_clockin_proto_goTypes,
		DependencyIndexes: file_api_clockin_admin_v1_clockin_proto_depIdxs,
		MessageInfos:      file_api_clockin_admin_v1_clockin_proto_msgTypes,
	}.Build()
	File_api_clockin_admin_v1_clockin_proto = out.File
	file_api_clockin_admin_v1_clockin_proto_rawDesc = nil
	file_api_clockin_admin_v1_clockin_proto_goTypes = nil
	file_api_clockin_admin_v1_clockin_proto_depIdxs = nil
}
