// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ReoordColumns holds the columns for the "reoord" table.
	ReoordColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user", Type: field.TypeInt64},
		{Name: "day", Type: field.TypeInt64},
		{Name: "type", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ReoordTable holds the schema information for the "reoord" table.
	ReoordTable = &schema.Table{
		Name:       "reoord",
		Columns:    ReoordColumns,
		PrimaryKey: []*schema.Column{ReoordColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "record_user_day_type",
				Unique:  true,
				Columns: []*schema.Column{ReoordColumns[1], ReoordColumns[2], ReoordColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ReoordTable,
	}
)

func init() {
	ReoordTable.Annotation = &entsql.Annotation{
		Table: "reoord",
	}
}
