// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/record/v1/record.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClockInOnWorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User int64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ClockInOnWorkRequest) Reset() {
	*x = ClockInOnWorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClockInOnWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInOnWorkRequest) ProtoMessage() {}

func (x *ClockInOnWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInOnWorkRequest.ProtoReflect.Descriptor instead.
func (*ClockInOnWorkRequest) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{0}
}

func (x *ClockInOnWorkRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

type ClockInOnWorkReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClockInOnWorkReply) Reset() {
	*x = ClockInOnWorkReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClockInOnWorkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInOnWorkReply) ProtoMessage() {}

func (x *ClockInOnWorkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInOnWorkReply.ProtoReflect.Descriptor instead.
func (*ClockInOnWorkReply) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{1}
}

type ClockInOffWorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User int64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ClockInOffWorkRequest) Reset() {
	*x = ClockInOffWorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClockInOffWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInOffWorkRequest) ProtoMessage() {}

func (x *ClockInOffWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInOffWorkRequest.ProtoReflect.Descriptor instead.
func (*ClockInOffWorkRequest) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{2}
}

func (x *ClockInOffWorkRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

type ClockInOffWorkReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClockInOffWorkReply) Reset() {
	*x = ClockInOffWorkReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_record_v1_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClockInOffWorkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInOffWorkReply) ProtoMessage() {}

func (x *ClockInOffWorkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_record_v1_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInOffWorkReply.ProtoReflect.Descriptor instead.
func (*ClockInOffWorkReply) Descriptor() ([]byte, []int) {
	return file_api_record_v1_record_proto_rawDescGZIP(), []int{3}
}

var File_api_record_v1_record_proto protoreflect.FileDescriptor

var file_api_record_v1_record_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x22, 0x2a, 0x0a, 0x14, 0x43,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x4f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x6e, 0x4f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2b, 0x0a,
	0x15, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x4f, 0x66, 0x66, 0x57, 0x6f, 0x72, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x4f, 0x66, 0x66, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0xc8, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x4f, 0x6e,
	0x57, 0x6f, 0x72, 0x6b, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x4f, 0x6e, 0x57, 0x6f,
	0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x6e, 0x4f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5c,
	0x0a, 0x0e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x4f, 0x66, 0x66, 0x57, 0x6f, 0x72, 0x6b,
	0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x4f, 0x66, 0x66, 0x57, 0x6f, 0x72, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x4f, 0x66,
	0x66, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x30, 0x0a, 0x0f,
	0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x50,
	0x01, 0x5a, 0x1b, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x2d, 0x69, 0x6e, 0x2f, 0x2e, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_record_v1_record_proto_rawDescOnce sync.Once
	file_api_record_v1_record_proto_rawDescData = file_api_record_v1_record_proto_rawDesc
)

func file_api_record_v1_record_proto_rawDescGZIP() []byte {
	file_api_record_v1_record_proto_rawDescOnce.Do(func() {
		file_api_record_v1_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_record_v1_record_proto_rawDescData)
	})
	return file_api_record_v1_record_proto_rawDescData
}

var file_api_record_v1_record_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_record_v1_record_proto_goTypes = []interface{}{
	(*ClockInOnWorkRequest)(nil),  // 0: api.record.v1.ClockInOnWorkRequest
	(*ClockInOnWorkReply)(nil),    // 1: api.record.v1.ClockInOnWorkReply
	(*ClockInOffWorkRequest)(nil), // 2: api.record.v1.ClockInOffWorkRequest
	(*ClockInOffWorkReply)(nil),   // 3: api.record.v1.ClockInOffWorkReply
}
var file_api_record_v1_record_proto_depIdxs = []int32{
	0, // 0: api.record.v1.RecordService.ClockInOnWork:input_type -> api.record.v1.ClockInOnWorkRequest
	2, // 1: api.record.v1.RecordService.ClockInOffWork:input_type -> api.record.v1.ClockInOffWorkRequest
	1, // 2: api.record.v1.RecordService.ClockInOnWork:output_type -> api.record.v1.ClockInOnWorkReply
	3, // 3: api.record.v1.RecordService.ClockInOffWork:output_type -> api.record.v1.ClockInOffWorkReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_record_v1_record_proto_init() }
func file_api_record_v1_record_proto_init() {
	if File_api_record_v1_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_record_v1_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClockInOnWorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_record_v1_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClockInOnWorkReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_record_v1_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClockInOffWorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_record_v1_record_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClockInOffWorkReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_record_v1_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_record_v1_record_proto_goTypes,
		DependencyIndexes: file_api_record_v1_record_proto_depIdxs,
		MessageInfos:      file_api_record_v1_record_proto_msgTypes,
	}.Build()
	File_api_record_v1_record_proto = out.File
	file_api_record_v1_record_proto_rawDesc = nil
	file_api_record_v1_record_proto_goTypes = nil
	file_api_record_v1_record_proto_depIdxs = nil
}
